name: qin_memo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  hooks_riverpod: ^0.14.0
  flutter_hooks:
  json_annotation:
  freezed_annotation:
  http:
  intl:
  dio:
  clipboard:
  image_picker:
  share:
  easy_debounce:
  shared_preferences:
  flutter_svg:
  webview_flutter:
  firebase_core:
  firebase_storage:
  flutter_cache_manager:

dev_dependencies:
  build_runner:
  freezed:
  json_serializable:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
