name: qin_memo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  hooks_riverpod:
  flutter_hooks:
  json_annotation:
  freezed_annotation:
  http:

dev_dependencies:
  build_runner:
  freezed:
  json_serializable:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
